package com.lms.module.ai.entity;

/**
 * Lifecycle states for a student's doubt resolution session.
 *
 * <ul>
 *   <li>{@link #PENDING}  — Doubt submitted, Kafka event published, awaiting RAG processing</li>
 *   <li>{@link #RESOLVED} — Answer generated by LLM and persisted</li>
 *   <li>{@link #FAILED}   — RAG pipeline failed after retries; routed to DLQ</li>
 * </ul>
 */
public enum DoubtStatus {
    PENDING,
    RESOLVED,
    FAILED
}
